apiVersion: v1
kind: Pod
spec:
  containers:
    - name: jnlp
      image: lalosam/jenkins-slave-mysql:3.1
      imagePullPolicy: Always
      env:
        - name: "LC_ALL" 
          value: "en_US.UTF-8"
        - name: "LANG"
          value: "en_US.UTF-8"
        - name: "TZ"
          value: "America/Chicago"
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "1Gi"
