apiVersion: v1
kind: Pod
spec:
  containers:
    - name: jnlp
      image: lalosam/jenkins-slave-mysql:3.1
      imagePullPolicy: Always
      workingDir: /home/jenkins
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "1Gi"
